// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xxx.proto

#ifndef PROTOBUF_INCLUDED_xxx_2eproto
#define PROTOBUF_INCLUDED_xxx_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xxx_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_xxx_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_xxx_2eproto();
namespace test {
class Testxxx;
class TestxxxDefaultTypeInternal;
extern TestxxxDefaultTypeInternal _Testxxx_default_instance_;
}  // namespace test
namespace google {
namespace protobuf {
template<> ::test::Testxxx* Arena::CreateMaybeMessage<::test::Testxxx>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace test {

// ===================================================================

class Testxxx final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.Testxxx) */ {
 public:
  Testxxx();
  virtual ~Testxxx();

  Testxxx(const Testxxx& from);

  inline Testxxx& operator=(const Testxxx& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Testxxx(Testxxx&& from) noexcept
    : Testxxx() {
    *this = ::std::move(from);
  }

  inline Testxxx& operator=(Testxxx&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Testxxx& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Testxxx* internal_default_instance() {
    return reinterpret_cast<const Testxxx*>(
               &_Testxxx_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Testxxx* other);
  friend void swap(Testxxx& a, Testxxx& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Testxxx* New() const final {
    return CreateMaybeMessage<Testxxx>(nullptr);
  }

  Testxxx* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Testxxx>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Testxxx& from);
  void MergeFrom(const Testxxx& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Testxxx* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 aa = 1;
  void clear_aa();
  static const int kAaFieldNumber = 1;
  ::google::protobuf::int32 aa() const;
  void set_aa(::google::protobuf::int32 value);

  // int32 bb = 2;
  void clear_bb();
  static const int kBbFieldNumber = 2;
  ::google::protobuf::int32 bb() const;
  void set_bb(::google::protobuf::int32 value);

  // int32 cc = 3;
  void clear_cc();
  static const int kCcFieldNumber = 3;
  ::google::protobuf::int32 cc() const;
  void set_cc(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:test.Testxxx)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 aa_;
  ::google::protobuf::int32 bb_;
  ::google::protobuf::int32 cc_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_xxx_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Testxxx

// int32 aa = 1;
inline void Testxxx::clear_aa() {
  aa_ = 0;
}
inline ::google::protobuf::int32 Testxxx::aa() const {
  // @@protoc_insertion_point(field_get:test.Testxxx.aa)
  return aa_;
}
inline void Testxxx::set_aa(::google::protobuf::int32 value) {
  
  aa_ = value;
  // @@protoc_insertion_point(field_set:test.Testxxx.aa)
}

// int32 bb = 2;
inline void Testxxx::clear_bb() {
  bb_ = 0;
}
inline ::google::protobuf::int32 Testxxx::bb() const {
  // @@protoc_insertion_point(field_get:test.Testxxx.bb)
  return bb_;
}
inline void Testxxx::set_bb(::google::protobuf::int32 value) {
  
  bb_ = value;
  // @@protoc_insertion_point(field_set:test.Testxxx.bb)
}

// int32 cc = 3;
inline void Testxxx::clear_cc() {
  cc_ = 0;
}
inline ::google::protobuf::int32 Testxxx::cc() const {
  // @@protoc_insertion_point(field_get:test.Testxxx.cc)
  return cc_;
}
inline void Testxxx::set_cc(::google::protobuf::int32 value) {
  
  cc_ = value;
  // @@protoc_insertion_point(field_set:test.Testxxx.cc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace test

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_xxx_2eproto
